export const GET_USER_INFO = 'GET_USER_INFO';
export const USER_ERROR = 'USERS_ERROR';

export const GET_USER_PLAYLISTS = 'GET_USER_PLAYLISTS';

export const GET_USER_TOP_TRACKS = 'GET_USER_TOP_TRACKS';
export const GET_USER_TOP_ARTISTS = 'GET_USER_TOP_ARTISTS';